// Industry-specific SEO keywords and optimization for Solar, Appliances, and 3C Electronics

export const industrySEO = {
  solar: {
    en: {
      keywords: [
        'solar panels', 'solar energy', 'photovoltaic', 'portable power station',
        'solar system', 'renewable energy', 'solar power', 'MPPT controller',
        'solar battery', 'solar inverter', 'off-grid solar', 'grid-tie solar',
        'solar installation', 'solar manufacturer', 'solar wholesale',
        'high efficiency solar', 'monocrystalline solar', 'polycrystalline solar',
      ],
      longTail: [
        'portable solar power station for camping',
        'high efficiency solar panels manufacturer',
        'wholesale solar panels China',
        'MPPT solar charge controller',
        'solar panel installation guide',
        'best portable power station 2024',
        'solar energy system for home',
        'commercial solar panel supplier',
      ],
      title: 'Solar Energy Systems | HousePlus - Professional Manufacturer',
      description: 'HousePlus manufactures high-efficiency solar panels and portable power stations. Wholesale solar solutions for residential and commercial use.',
    },
    es: {
      keywords: [
        'paneles solares', 'energía solar', 'fotovoltaica', 'estación de energía portátil',
        'sistema solar', 'energía renovable', 'energía solar', 'controlador MPPT',
        'batería solar', 'inversor solar', 'solar fuera de la red', 'solar conectado a la red',
        'instalación solar', 'fabricante solar', 'mayorista solar',
        'paneles solares de alta eficiencia', 'solar monocristalino', 'solar policristalino',
      ],
      longTail: [
        'estación de energía solar portátil para camping',
        'fabricante de paneles solares de alta eficiencia',
        'paneles solares mayorista China',
        'controlador de carga solar MPPT',
        'guía de instalación de paneles solares',
        'mejor estación de energía portátil 2024',
        'sistema de energía solar para el hogar',
        'proveedor de paneles solares comerciales',
      ],
      title: 'Sistemas de Energía Solar | HousePlus - Fabricante Profesional',
      description: 'HousePlus fabrica paneles solares de alta eficiencia y estaciones de energía portátiles. Soluciones solares mayoristas para uso residencial y comercial.',
    },
    de: {
      keywords: [
        'Solarpanels', 'Solarenergie', 'Photovoltaik', 'tragbares Kraftwerk',
        'Solarsystem', 'erneuerbare Energie', 'Solarstrom', 'MPPT-Regler',
        'Solarbatterie', 'Solarwechselrichter', 'netzunabhängige Solaranlage', 'netzgebundene Solaranlage',
        'Solarinstallation', 'Solarhersteller', 'Solargroßhandel',
        'hocheffiziente Solarpanels', 'monokristalline Solaranlage', 'polykristalline Solaranlage',
      ],
      longTail: [
        'tragbares Solarkraftwerk zum Camping',
        'hocheffizienter Solarpanel-Hersteller',
        'Solarpanels Großhandel China',
        'MPPT-Solarladeregler',
        'Anleitung zur Solarinstallation',
        'bestes tragbares Kraftwerk 2024',
        'Solarsystem für Zuhause',
        'kommerzieller Solarpanel-Lieferant',
      ],
      title: 'Solarsysteme | HousePlus - Professioneller Hersteller',
      description: 'HousePlus stellt hocheffiziente Solarpanels und tragbare Kraftwerke her. Großhandels-Solarlösungen für Wohn- und Gewerbenutzung.',
    },
    fr: {
      keywords: [
        'panneaux solaires', 'énergie solaire', 'photovoltaïque', 'centrale électrique portable',
        'système solaire', 'énergie renouvelable', 'puissance solaire', 'contrôleur MPPT',
        'batterie solaire', 'onduleur solaire', 'système solaire autonome', 'système solaire connecté au réseau',
        'installation solaire', 'fabricant solaire', 'gros solaire',
        'panneaux solaires haute efficacité', 'solaire monocristallin', 'solaire polycristallin',
      ],
      longTail: [
        'centrale électrique solaire portable pour le camping',
        'fabricant de panneaux solaires haute efficacité',
        'panneaux solaires gros China',
        'contrôleur de charge solaire MPPT',
        'guide d\'installation de panneaux solaires',
        'meilleure centrale électrique portable 2024',
        'système d\'énergie solaire pour la maison',
        'fournisseur de panneaux solaires commerciaux',
      ],
      title: 'Systèmes d\'Énergie Solaire | HousePlus - Fabricant Professionnel',
      description: 'HousePlus fabrique des panneaux solaires haute efficacité et des centrales électriques portables. Solutions solaires en gros pour usage résidentiel et commercial.',
    },
    ar: {
      keywords: [
        'الألواح الشمسية', 'الطاقة الشمسية', 'الفوتوفولطية', 'محطة الطاقة المحمولة',
        'النظام الشمسي', 'الطاقة المتجددة', 'الطاقة الشمسية', 'وحدة تحكم MPPT',
        'البطارية الشمسية', 'العاكس الشمسي', 'النظام الشمسي خارج الشبكة', 'النظام الشمسي المتصل بالشبكة',
        'التثبيت الشمسي', 'الشركة المصنعة للطاقة الشمسية', 'الجملة الشمسية',
        'الألواح الشمسية عالية الكفاءة', 'الشمسية أحادية البلورة', 'الشمسية متعددة البلورات',
      ],
      longTail: [
        'محطة الطاقة الشمسية المحمولة للتخييم',
        'الشركة المصنعة للألواح الشمسية عالية الكفاءة',
        'الألواح الشمسية بالجملة الصين',
        'وحدة تحكم شحن الطاقة الشمسية MPPT',
        'دليل تثبيت الألواح الشمسية',
        'أفضل محطة طاقة محمولة 2024',
        'نظام الطاقة الشمسية للمنزل',
        'مورد الألواح الشمسية التجارية',
      ],
      title: 'أنظمة الطاقة الشمسية | HousePlus - الشركة المصنعة المهنية',
      description: 'تصنع HousePlus الألواح الشمسية عالية الكفاءة ومحطات الطاقة المحمولة. حلول الطاقة الشمسية بالجملة للاستخدام السكني والتجاري.',
    },
  },
  appliances: {
    en: {
      keywords: [
        'home appliances', 'kitchen appliances', 'washing machine', 'refrigerator',
        'microwave', 'dishwasher', 'air conditioner', 'water heater',
        'vacuum cleaner', 'electric oven', 'cooktop', 'range hood',
        'appliance manufacturer', 'wholesale appliances', 'smart appliances',
        'energy efficient appliances', 'home appliance supplier',
      ],
      longTail: [
        'best energy efficient washing machines',
        'wholesale home appliances supplier China',
        'smart kitchen appliances 2024',
        'commercial refrigerator manufacturer',
        'home appliance wholesale prices',
        'durable washing machine brands',
        'energy saving air conditioner',
        'professional kitchen appliances supplier',
      ],
      title: 'Home Appliances | HousePlus - Quality Manufacturer',
      description: 'HousePlus manufactures premium home appliances including washing machines, refrigerators, and kitchen solutions. Wholesale appliances for residential use.',
    },
    es: {
      keywords: [
        'electrodomésticos', 'electrodomésticos de cocina', 'lavadora', 'refrigerador',
        'microondas', 'lavavajillas', 'aire acondicionado', 'calentador de agua',
        'aspiradora', 'horno eléctrico', 'placa de cocción', 'campana extractora',
        'fabricante de electrodomésticos', 'electrodomésticos mayorista', 'electrodomésticos inteligentes',
        'electrodomésticos eficientes energéticamente', 'proveedor de electrodomésticos',
      ],
      longTail: [
        'mejores lavadoras eficientes energéticamente',
        'proveedor mayorista de electrodomésticos China',
        'electrodomésticos de cocina inteligentes 2024',
        'fabricante de refrigerador comercial',
        'precios mayoristas de electrodomésticos',
        'marcas de lavadora duraderas',
        'aire acondicionado ahorrador de energía',
        'proveedor profesional de electrodomésticos de cocina',
      ],
      title: 'Electrodomésticos | HousePlus - Fabricante de Calidad',
      description: 'HousePlus fabrica electrodomésticos premium incluyendo lavadoras, refrigeradores y soluciones de cocina. Electrodomésticos mayoristas para uso residencial.',
    },
    de: {
      keywords: [
        'Haushaltsgeräte', 'Küchengeräte', 'Waschmaschine', 'Kühlschrank',
        'Mikrowelle', 'Geschirrspüler', 'Klimaanlage', 'Warmwasserbereiter',
        'Staubsauger', 'Elektroherd', 'Kochfeld', 'Dunstabzugshaube',
        'Haushaltsgerätehersteller', 'Haushaltsgeräte Großhandel', 'Smart-Geräte',
        'energieeffiziente Haushaltsgeräte', 'Haushaltsgerätelieferant',
      ],
      longTail: [
        'beste energieeffiziente Waschmaschinen',
        'Großhandel Haushaltsgeräte Lieferant China',
        'intelligente Küchengeräte 2024',
        'Hersteller von Gewerbekühlschränken',
        'Großhandelspreise für Haushaltsgeräte',
        'langlebige Waschmaschinenmarken',
        'energiesparende Klimaanlage',
        'professioneller Lieferant von Küchengeräten',
      ],
      title: 'Haushaltsgeräte | HousePlus - Qualitätshersteller',
      description: 'HousePlus stellt hochwertige Haushaltsgeräte her, darunter Waschmaschinen, Kühlschränke und Küchengeräte. Großhandels-Haushaltsgeräte für den Wohngebrauch.',
    },
    fr: {
      keywords: [
        'électroménagers', 'électroménagers de cuisine', 'machine à laver', 'réfrigérateur',
        'micro-ondes', 'lave-vaisselle', 'climatiseur', 'chauffe-eau',
        'aspirateur', 'four électrique', 'plaque de cuisson', 'hotte aspirante',
        'fabricant d\'électroménagers', 'électroménagers gros', 'électroménagers intelligents',
        'électroménagers économes en énergie', 'fournisseur d\'électroménagers',
      ],
      longTail: [
        'meilleures machines à laver économes en énergie',
        'fournisseur gros électroménagers China',
        'électroménagers de cuisine intelligents 2024',
        'fabricant de réfrigérateur commercial',
        'prix gros électroménagers',
        'marques de machines à laver durables',
        'climatiseur économe en énergie',
        'fournisseur professionnel d\'électroménagers de cuisine',
      ],
      title: 'Électroménagers | HousePlus - Fabricant de Qualité',
      description: 'HousePlus fabrique des électroménagers premium incluant machines à laver, réfrigérateurs et solutions de cuisine. Électroménagers gros pour usage résidentiel.',
    },
    ar: {
      keywords: [
        'الأجهزة المنزلية', 'أجهزة المطبخ', 'غسالة', 'ثلاجة',
        'ميكروويف', 'غسالة الأطباق', 'مكيف الهواء', 'سخان الماء',
        'مكنسة كهربائية', 'فرن كهربائي', 'موقد', 'شفاط المطبخ',
        'الشركة المصنعة للأجهزة المنزلية', 'الأجهزة المنزلية بالجملة', 'الأجهزة الذكية',
        'الأجهزة المنزلية الموفرة للطاقة', 'مورد الأجهزة المنزلية',
      ],
      longTail: [
        'أفضل غسالات موفرة للطاقة',
        'مورد الأجهزة المنزلية بالجملة الصين',
        'أجهزة المطبخ الذكية 2024',
        'الشركة المصنعة للثلاجة التجارية',
        'أسعار الأجهزة المنزلية بالجملة',
        'علامات تجارية غسالة متينة',
        'مكيف هواء موفر للطاقة',
        'مورد أجهزة المطبخ المهنية',
      ],
      title: 'الأجهزة المنزلية | HousePlus - الشركة المصنعة للجودة',
      description: 'تصنع HousePlus أجهزة منزلية فاخرة بما في ذلك الغسالات والثلاجات وحلول المطبخ. أجهزة منزلية بالجملة للاستخدام السكني.',
    },
  },
  electronics: {
    en: {
      keywords: [
        '3C electronics', 'smart home', 'LED lighting', 'smart speaker',
        'wireless charger', 'power bank', 'USB cable', 'phone accessories',
        'smart bulb', 'smart plug', 'smart thermostat', 'security camera',
        'electronics manufacturer', 'wholesale electronics', 'digital devices',
        'consumer electronics', 'smart device supplier',
      ],
      longTail: [
        'best smart home devices 2024',
        'wholesale 3C electronics China',
        'LED smart bulb manufacturer',
        'professional power bank supplier',
        'smart home automation system',
        'high quality USB cables wholesale',
        'smart speaker with voice control',
        'affordable wireless chargers',
      ],
      title: '3C Digital Electronics | HousePlus - Smart Solutions',
      description: 'HousePlus manufactures 3C digital electronics including smart home devices, LED lighting, and consumer electronics. Wholesale smart device solutions.',
    },
    es: {
      keywords: [
        'electrónica 3C', 'hogar inteligente', 'iluminación LED', 'altavoz inteligente',
        'cargador inalámbrico', 'banco de energía', 'cable USB', 'accesorios de teléfono',
        'bombilla inteligente', 'enchufe inteligente', 'termostato inteligente', 'cámara de seguridad',
        'fabricante de electrónica', 'electrónica mayorista', 'dispositivos digitales',
        'electrónica de consumo', 'proveedor de dispositivos inteligentes',
      ],
      longTail: [
        'mejores dispositivos de hogar inteligente 2024',
        'electrónica 3C mayorista China',
        'fabricante de bombilla LED inteligente',
        'proveedor profesional de banco de energía',
        'sistema de automatización del hogar inteligente',
        'cables USB de alta calidad mayorista',
        'altavoz inteligente con control de voz',
        'cargadores inalámbricos asequibles',
      ],
      title: 'Electrónica Digital 3C | HousePlus - Soluciones Inteligentes',
      description: 'HousePlus fabrica electrónica digital 3C incluyendo dispositivos de hogar inteligente, iluminación LED y electrónica de consumo. Soluciones de dispositivos inteligentes mayoristas.',
    },
    de: {
      keywords: [
        '3C-Elektronik', 'Smart Home', 'LED-Beleuchtung', 'intelligenter Lautsprecher',
        'kabelloses Ladegerät', 'Powerbank', 'USB-Kabel', 'Telefonzubehör',
        'intelligente Glühbirne', 'intelligente Steckdose', 'intelligentes Thermostat', 'Sicherheitskamera',
        'Elektronikhersteller', 'Elektronik Großhandel', 'digitale Geräte',
        'Unterhaltungselektronik', 'Lieferant intelligenter Geräte',
      ],
      longTail: [
        'beste Smart-Home-Geräte 2024',
        '3C-Elektronik Großhandel China',
        'Hersteller intelligenter LED-Glühbirnen',
        'professioneller Powerbank-Lieferant',
        'intelligentes Heimautomationssystem',
        'hochwertige USB-Kabel Großhandel',
        'intelligenter Lautsprecher mit Sprachsteuerung',
        'erschwingliche kabellose Ladegeräte',
      ],
      title: '3C Digitalelektronik | HousePlus - Intelligente Lösungen',
      description: 'HousePlus stellt 3C-Digitalelektronik her, darunter Smart-Home-Geräte, LED-Beleuchtung und Unterhaltungselektronik. Großhandels-Smart-Device-Lösungen.',
    },
    fr: {
      keywords: [
        'électronique 3C', 'maison intelligente', 'éclairage LED', 'haut-parleur intelligent',
        'chargeur sans fil', 'batterie externe', 'câble USB', 'accessoires téléphone',
        'ampoule intelligente', 'prise intelligente', 'thermostat intelligent', 'caméra de sécurité',
        'fabricant d\'électronique', 'électronique gros', 'appareils numériques',
        'électronique grand public', 'fournisseur d\'appareils intelligents',
      ],
      longTail: [
        'meilleurs appareils maison intelligente 2024',
        'électronique 3C gros China',
        'fabricant d\'ampoule LED intelligente',
        'fournisseur professionnel de batterie externe',
        'système domotique intelligent',
        'câbles USB haute qualité gros',
        'haut-parleur intelligent avec contrôle vocal',
        'chargeurs sans fil abordables',
      ],
      title: 'Électronique Numérique 3C | HousePlus - Solutions Intelligentes',
      description: 'HousePlus fabrique l\'électronique numérique 3C incluant appareils maison intelligente, éclairage LED et électronique grand public. Solutions d\'appareils intelligents gros.',
    },
    ar: {
      keywords: [
        'إلكترونيات 3C', 'المنزل الذكي', 'إضاءة LED', 'مكبر صوت ذكي',
        'شاحن لاسلكي', 'بنك الطاقة', 'كابل USB', 'اكسسوارات الهاتف',
        'مصباح ذكي', 'مقبس ذكي', 'منظم حرارة ذكي', 'كاميرا الأمان',
        'الشركة المصنعة للإلكترونيات', 'الإلكترونيات بالجملة', 'الأجهزة الرقمية',
        'الإلكترونيات الاستهلاكية', 'مورد الأجهزة الذكية',
      ],
      longTail: [
        'أفضل أجهزة المنزل الذكي 2024',
        'إلكترونيات 3C بالجملة الصين',
        'الشركة المصنعة لمصباح LED الذكي',
        'مورد بنك الطاقة المهني',
        'نظام أتمتة المنزل الذكي',
        'كابلات USB عالية الجودة بالجملة',
        'مكبر صوت ذكي مع التحكم الصوتي',
        'شواحن لاسلكية بأسعار معقولة',
      ],
      title: 'الإلكترونيات الرقمية 3C | HousePlus - حلول ذكية',
      description: 'تصنع HousePlus الإلكترونيات الرقمية 3C بما في ذلك أجهزة المنزل الذكي والإضاءة LED والإلكترونيات الاستهلاكية. حلول الأجهزة الذكية بالجملة.',
    },
  },
};

export function getIndustryKeywords(industry: 'solar' | 'appliances' | 'electronics', lang: string = 'en') {
  const industryData = industrySEO[industry];
  const langData = industryData[lang as keyof typeof industryData] || industryData.en;
  return langData;
}
