// Static product data — sourced from Storyblok CMS and embedded for reliable SSR
// Last synced: 2026-04-24

export interface ProductSpec {
  key: string;
  value: string;
}

export interface ProductFAQ {
  question: string;
  answer: string;
}

export interface B2BInfo {
  moq: string;
  leadTime: string;
  warranty: string;
  certifications: string[];
  oemOdm: boolean;
  factorySize: string;
  foundedYear: number;
  exportCountries: number;
  wholesaleClients: number;
}

export interface ProductData {
  name: string;
  category: 'solar' | 'appliances' | 'electronics';
  description: string;
  geoDescription?: string;
  applications: string;
  specs: ProductSpec[];
  features: string[];
  coverImage: string;
  badge?: string;
  faq?: ProductFAQ[];
  b2bInfo?: B2BInfo;
}

export const PRODUCT_DATA: Record<string, ProductData> = {
  'solar-panel-500w': {
    name: '500W Monocrystalline Solar Panel',
    category: 'solar',
    badge: 'Best Seller',
    description: 'High-efficiency monocrystalline solar panel with 21.5% conversion rate, engineered for residential, commercial and off-grid installations worldwide.',
    applications: 'Rooftop solar systems, off-grid cabins, commercial solar farms, agricultural irrigation.',
    specs: [
      { key: 'Model', value: 'HP-SP500' },
      { key: 'Peak Power', value: '500W' },
      { key: 'Cell Type', value: 'Monocrystalline PERC' },
      { key: 'Efficiency', value: '21.5%' },
    ],
    features: [
      'Anti-reflective tempered glass surface for maximum light absorption',
      'Anodised aluminium alloy frame — corrosion-resistant and lightweight',
      'IP68-rated junction box with bypass diodes for shading protection',
    ],
    coverImage: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=900&q=85',
  },
  'solar-inverter-3kw': {
    name: '3kW Pure Sine Wave Solar Inverter',
    category: 'solar',
    badge: 'CE Certified',
    description: 'Pure sine wave output inverter with built-in MPPT charge controller. Supports both grid-tie and off-grid operation for flexible deployment.',
    applications: 'Residential solar systems, small commercial installations, backup power solutions.',
    specs: [
      { key: 'Model', value: 'HP-INV3000' },
      { key: 'Rated Power', value: '3000W' },
      { key: 'Output Waveform', value: 'Pure Sine Wave' },
      { key: 'MPPT Efficiency', value: '≥99%' },
    ],
    features: [
      'Built-in MPPT charge controller with 99%+ tracking efficiency',
      'LCD display with real-time monitoring of voltage, current and power',
      'Multi-protection: over-voltage, over-current, short-circuit, thermal',
    ],
    coverImage: 'https://images.unsplash.com/photo-1620216503901-515bb5c34c30?w=900&q=85',
  },
  'lithium-battery-5kwh': {
    name: '5kWh LiFePO4 Lithium Battery',
    category: 'solar',
    badge: 'New',
    description: 'Long-cycle LiFePO4 battery pack with integrated BMS. Designed for solar energy storage with 6000+ charge cycles and a 10-year design life.',
    applications: 'Home solar energy storage, commercial backup power, off-grid systems.',
    specs: [
      { key: 'Model', value: 'HP-LFP5K' },
      { key: 'Capacity', value: '5kWh' },
      { key: 'Chemistry', value: 'LiFePO4' },
      { key: 'Cycle Life', value: '6000+ cycles' },
    ],
    features: [
      'Integrated BMS with cell balancing and temperature management',
      'Wide operating temperature range: -20°C to +60°C',
      'Stackable design — expandable to 30kWh with parallel connection',
    ],
    coverImage: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900&q=85',
  },
  'lead-acid-battery-100ah': {
    name: '100Ah Deep Cycle Lead-Acid Battery',
    category: 'solar',
    description: 'Maintenance-free VRLA deep-cycle battery suitable for solar storage, UPS and marine applications. Reliable performance in demanding environments.',
    applications: 'Solar energy storage, UPS backup, marine and RV applications.',
    specs: [
      { key: 'Model', value: 'HP-LA100' },
      { key: 'Capacity', value: '100Ah' },
      { key: 'Voltage', value: '12V' },
      { key: 'Type', value: 'VRLA AGM' },
    ],
    features: [
      'Valve-regulated sealed design — zero maintenance required',
      'Deep discharge recovery capability for extended service life',
      'Vibration-resistant construction for mobile and marine use',
    ],
    coverImage: 'https://images.unsplash.com/photo-1619641151040-af3bf8325790?w=900&q=85',
  },
  'charge-controller-60a': {
    name: 'MPPT Solar Charge Controller 60A',
    category: 'solar',
    description: 'Advanced MPPT algorithm with 99.5% tracking efficiency. LCD display, multi-protection, supports 12V/24V/48V battery systems.',
    applications: 'Off-grid solar systems, RV solar charging, remote monitoring stations.',
    specs: [
      { key: 'Model', value: 'HP-MPPT60' },
      { key: 'Max Charge Current', value: '60A' },
      { key: 'MPPT Efficiency', value: '99.5%' },
      { key: 'System Voltage', value: '12V/24V/48V Auto' },
    ],
    features: [
      'Advanced MPPT algorithm with 99.5% maximum power point tracking',
      'Backlit LCD display showing PV voltage, battery voltage and charge current',
      'Comprehensive protection: overcharge, over-discharge, short-circuit, reverse polarity',
    ],
    coverImage: 'https://images.unsplash.com/photo-1558444458-5f75bc94476c?w=900&q=85',
  },
  'solar-street-light-200w': {
    name: '200W All-in-One Solar Street Light',
    category: 'solar',
    description: 'Integrated solar panel, lithium battery and LED light in a single unit. Motion sensor, remote control, IP65 waterproof for outdoor installation.',
    applications: 'Street lighting, car parks, pathways, industrial yards, rural electrification.',
    specs: [
      { key: 'Model', value: 'HP-SSL200' },
      { key: 'LED Power', value: '200W' },
      { key: 'Battery', value: '60Ah LiFePO4' },
      { key: 'IP Rating', value: 'IP65' },
    ],
    features: [
      'All-in-one design — no external wiring required for installation',
      'PIR motion sensor with adjustable sensitivity and delay time',
      'Remote control for brightness adjustment and scheduling',
    ],
    coverImage: 'https://images.unsplash.com/photo-1542641728-6ca359b085f4?w=900&q=85',
  },
  'solar-fan-20w': {
    name: 'DC Solar Fan 20W',
    category: 'solar',
    description: 'Brushless DC motor fan powered directly by solar panel. Ideal for ventilation in off-grid cabins, greenhouses and livestock shelters.',
    applications: 'Greenhouse ventilation, livestock shelters, off-grid cabins, solar-powered workshops.',
    specs: [
      { key: 'Model', value: 'HP-SF20' },
      { key: 'Power', value: '20W' },
      { key: 'Voltage', value: '12V/24V DC' },
      { key: 'Airflow', value: '1200 m³/h' },
    ],
    features: [
      'Brushless DC motor for silent, efficient and long-lasting operation',
      'Direct solar panel connection — no battery required in daylight',
      'Corrosion-resistant ABS housing for outdoor and humid environments',
    ],
    coverImage: 'https://images.unsplash.com/photo-1565151443325814491ebe?w=900&q=85',
  },
  'solar-power-bank-20000mah': {
    name: '20000mAh Solar Power Bank',
    category: 'solar',
    description: 'Dual USB + USB-C output with 18W PD fast charge. Waterproof casing with built-in solar charging panel for outdoor and emergency use.',
    applications: 'Outdoor activities, camping, emergency backup power, travel charging.',
    specs: [
      { key: 'Model', value: 'HP-SPB20K' },
      { key: 'Capacity', value: '20000mAh' },
      { key: 'Output', value: 'USB-A ×2 + USB-C' },
      { key: 'Fast Charge', value: '18W PD' },
    ],
    features: [
      '18W USB-C PD fast charging for smartphones and tablets',
      'Built-in solar panel for emergency top-up in outdoor environments',
      'IPX4 waterproof and dustproof construction',
    ],
    coverImage: 'https://images.unsplash.com/photo-1609091839311-d53681962025?w=900&q=85',
  },
  'air-fryer-5-8l': {
    name: '5.8L Digital Air Fryer',
    category: 'appliances',
    badge: 'Top Rated',
    description: 'Large-capacity digital air fryer with 8 preset programmes, touch panel and 360° rapid air circulation technology for healthier, oil-free cooking.',
    applications: 'Home kitchens, catering, hospitality, food service businesses.',
    specs: [
      { key: 'Model', value: 'HP-AF58' },
      { key: 'Capacity', value: '5.8L' },
      { key: 'Power', value: '1700W' },
      { key: 'Temperature Range', value: '80–200°C' },
    ],
    features: [
      'Oil-free cooking with up to 80% less fat than traditional frying',
      'Digital touch screen with 8 one-touch preset programmes',
      '360° rapid air circulation for even, crispy results',
    ],
    coverImage: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=900&q=85',
  },
  'induction-cooktop-2000w': {
    name: '2000W Induction Cooktop',
    category: 'appliances',
    description: 'Slim ceramic glass induction cooktop with 10 power levels, child lock and automatic pan detection. CE and RoHS certified for global markets.',
    applications: 'Home kitchens, hotel rooms, catering, student accommodation.',
    specs: [
      { key: 'Model', value: 'HP-IC2000' },
      { key: 'Power', value: '2000W' },
      { key: 'Power Levels', value: '10' },
      { key: 'Surface', value: 'Schott Ceran Glass' },
    ],
    features: [
      'Schott Ceran glass surface — scratch-resistant and easy to clean',
      'Automatic pan detection — powers off when no cookware is detected',
      'Child lock and 3-hour auto shut-off for safety',
    ],
    coverImage: 'https://images.unsplash.com/photo-1624452085375-343547842776?w=900&q=85',
  },
  'electric-kettle-1-5l': {
    name: '1.5L Stainless Steel Electric Kettle',
    category: 'appliances',
    description: 'BPA-free stainless steel interior with 1500W rapid boil, 360° cordless base and auto shut-off with boil-dry protection.',
    applications: 'Home use, office kitchens, hotel rooms, hospitality.',
    specs: [
      { key: 'Model', value: 'HP-EK15' },
      { key: 'Capacity', value: '1.5L' },
      { key: 'Power', value: '1500W' },
      { key: 'Material', value: 'BPA-free Stainless Steel' },
    ],
    features: [
      'BPA-free stainless steel interior for clean, safe water heating',
      '1500W rapid boil — 1.5L in under 3 minutes',
      '360° cordless base with auto shut-off and boil-dry protection',
    ],
    coverImage: 'https://images.unsplash.com/photo-1594212699903-ec8a3ecc50f1?w=900&q=85',
  },
  'toaster-2-slice': {
    name: '2-Slice Stainless Steel Toaster',
    category: 'appliances',
    description: 'Wide-slot toaster with 7 browning settings, removable crumb tray, cancel/reheat/defrost functions and stainless steel housing.',
    applications: 'Home kitchens, hotel breakfast service, office pantries.',
    specs: [
      { key: 'Model', value: 'HP-TS2' },
      { key: 'Slots', value: '2 Wide Slots' },
      { key: 'Power', value: '850W' },
      { key: 'Settings', value: '7 Browning Levels' },
    ],
    features: [
      '7 browning settings for precise toast control',
      'Extra-wide slots accommodate thick-cut bread and bagels',
      'Removable crumb tray for easy cleaning',
    ],
    coverImage: 'https://images.unsplash.com/photo-1584905066893-7d5c142ba4e1?w=900&q=85',
  },
  'headphone-over-ear': {
    name: 'Over-Ear Headphone with Microphone',
    category: 'electronics',
    badge: 'Popular',
    description: 'Foldable over-ear headphone with 40mm drivers, built-in microphone and 3.5mm universal jack. Ideal for gaming, calls and music.',
    applications: 'Gaming, remote work calls, music listening, multimedia.',
    specs: [
      { key: 'Model', value: 'HP-HE01' },
      { key: 'Driver Size', value: '40mm' },
      { key: 'Frequency Response', value: '20Hz–20kHz' },
      { key: 'Connector', value: '3.5mm Universal Jack' },
    ],
    features: [
      '40mm neodymium drivers for rich, detailed sound reproduction',
      'Omnidirectional built-in microphone for clear voice communication',
      'Foldable design with padded headband for comfortable extended wear',
    ],
    coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&q=85',
  },
  'bluetooth-earphone-tws': {
    name: 'True Wireless Bluetooth Earphones (TWS)',
    category: 'electronics',
    badge: 'New',
    description: 'Bluetooth 5.3 TWS earbuds with active noise cancellation, 6-hour playtime plus 24-hour charging case, IPX5 water resistance.',
    applications: 'Sports and fitness, commuting, remote work, everyday listening.',
    specs: [
      { key: 'Model', value: 'HP-TWS01' },
      { key: 'Bluetooth', value: '5.3' },
      { key: 'Playtime', value: '6h + 24h (case)' },
      { key: 'Water Resistance', value: 'IPX5' },
    ],
    features: [
      'Bluetooth 5.3 with low-latency mode for gaming and video',
      'Active noise cancellation (ANC) with transparency mode',
      'IPX5 sweat and water resistance for sports use',
    ],
    coverImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&q=85',
  },
  'smart-watch': {
    name: 'Smart Watch with Heart Rate Monitor',
    category: 'electronics',
    description: '1.7" colour touch screen, heart rate + SpO2 monitoring, 20+ sport modes, 7-day battery life, IP68 waterproof.',
    applications: 'Fitness tracking, health monitoring, everyday smart notifications.',
    specs: [
      { key: 'Model', value: 'HP-SW01' },
      { key: 'Display', value: '1.7" TFT Colour Touch' },
      { key: 'Battery Life', value: '7 days' },
      { key: 'Water Resistance', value: 'IP68' },
    ],
    features: [
      'Continuous heart rate and SpO2 blood oxygen monitoring',
      '20+ sport modes with automatic activity recognition',
      'IP68 waterproof — safe for swimming and showering',
    ],
    coverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=85',
  },
  'portable-ssd-1tb': {
    name: '1TB USB-C Portable SSD',
    category: 'electronics',
    description: 'Read up to 1050 MB/s, write up to 1000 MB/s. Shock-resistant aluminium casing, USB 3.2 Gen 2 interface, pocket-sized.',
    applications: 'Video editing, data backup, creative professionals, field data collection.',
    specs: [
      { key: 'Model', value: 'HP-SSD1T' },
      { key: 'Capacity', value: '1TB' },
      { key: 'Read Speed', value: '1050 MB/s' },
      { key: 'Interface', value: 'USB 3.2 Gen 2 (USB-C)' },
    ],
    features: [
      'Read up to 1050 MB/s for rapid large file transfers',
      'Shock-resistant aluminium alloy casing — drop-tested to 2m',
      'Compact pocket-sized form factor — 50g lightweight',
    ],
    coverImage: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?w=900&q=85',
  },
  'micro-sd-128gb': {
    name: '128GB Micro SD Card (Class 10 / A2)',
    category: 'electronics',
    description: 'UHS-I U3 A2 rated micro SD card. Up to 100 MB/s read, 90 MB/s write. Waterproof, temperature-proof, X-ray-proof.',
    applications: 'Smartphones, action cameras, drones, dashcams, tablets.',
    specs: [
      { key: 'Model', value: 'HP-SD128' },
      { key: 'Capacity', value: '128GB' },
      { key: 'Read Speed', value: '100 MB/s' },
      { key: 'Rating', value: 'UHS-I U3 A2 Class 10' },
    ],
    features: [
      'A2 app performance rating for smooth app loading on Android devices',
      'Waterproof, temperature-proof and X-ray-proof construction',
      'Includes full-size SD adapter for camera and laptop compatibility',
    ],
    coverImage: 'https://images.unsplash.com/photo-1558478551-1a378f63ad28?w=900&q=85',
  },
  'usb-c-cable-2m': {
    name: 'Fast Charging USB-C Cable 2m',
    category: 'electronics',
    description: '100W USB-C to USB-C braided cable. Supports PD 3.0, QC 4.0 and 480 Mbps data transfer. 2-metre length with durable nylon braid.',
    applications: 'Laptop charging, smartphone fast charging, data transfer.',
    specs: [
      { key: 'Model', value: 'HP-CC2M' },
      { key: 'Length', value: '2m' },
      { key: 'Max Power', value: '100W' },
      { key: 'Data Transfer', value: '480 Mbps' },
    ],
    features: [
      '100W power delivery — charges laptops, tablets and phones at full speed',
      'Supports PD 3.0 and QC 4.0 fast charging protocols',
      'Braided nylon jacket with aluminium connectors — 10,000+ bend cycles',
    ],
    coverImage: 'https://images.unsplash.com/photo-1619193100632-68046777174b?w=900&q=85',
  },

  // ===== P0 GEO-Optimized Products (Added 2026-06-26) =====
  'solar-panel-100w': {
    name: '100W Monocrystalline Solar Panel',
    category: 'solar',
    badge: 'Best Seller',
    description: 'High-efficiency 100W monocrystalline solar panel with >=21% conversion rate. Engineered for RV, marine, off-grid cabin and outdoor camping applications.',
    geoDescription: 'HousePlus 100W monocrystalline solar panel delivers >=21% conversion efficiency from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Panel dimensions: 1010x510x30 mm, weight 6.8 kg. Operating temperature: -40C to +85C. IP65 waterproof rating. MOQ 100 pcs, lead time 20-25 days. 24-month warranty. CE, IEC, RoHS certified.',
    applications: 'RV roof installations, marine systems, off-grid cabins, outdoor camping, remote monitoring stations.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-100W' },
      { key: 'Peak Power', value: '100W' },
      { key: 'Cell Type', value: 'Monocrystalline' },
      { key: 'Efficiency', value: '>=21%' },
      { key: 'Dimensions', value: '1010x510x30 mm' },
      { key: 'Weight', value: '6.8 kg' },
      { key: 'Operating Temp', value: '-40C to +85C' },
      { key: 'IP Rating', value: 'IP65' },
    ],
    features: [
      '>=21% cell efficiency from monocrystalline silicon wafers',
      'Anodised aluminium alloy frame -- corrosion-resistant for marine use',
      'IP65-rated junction box with bypass diodes for shading protection',
      'Tempered glass surface with anti-reflective coating',
    ],
    faq: [
      { question: 'What is the MOQ for the 100W solar panel?', answer: 'MOQ is 100 pcs. Volume pricing starts at 500 pcs with 12% discount.' },
      { question: 'What certifications does this panel have?', answer: 'CE, IEC, RoHS certified. ISO 9001 factory. UN38.3 available on request for battery-integrated orders.' },
      { question: 'What is the lead time for 100W panels?', answer: '20-25 days for 100-500 pcs. 30-35 days for 1000+ pcs.' },
      { question: 'Can I order custom frame colours?', answer: 'Yes, black and silver frames standard. Custom Pantone colours from 500+ pcs.' },
      { question: 'What is the warranty period?', answer: '24-month warranty against manufacturing defects. Replacement shipped within 72 hours.' },
      { question: 'How many panels fit in a 40HQ container?', answer: 'Approximately 650 units per 40HQ container. Mixed SKU loading available.' },
      { question: 'Do you provide OEM packaging?', answer: 'Yes. Custom boxes, manuals, and branding from MOQ 100 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '100 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'IEC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=900&q=85',
  },
  'portable-power-station-3000w': {
    name: '3000W Portable Power Station',
    category: 'solar',
    badge: 'Best Seller',
    description: '3000Wh LiFePO4 portable power station with 3000W continuous output (6000W peak). Supports solar, AC, and car charging. Ideal for outdoor construction, emergency backup, and camping.',
    geoDescription: 'HousePlus 3000W portable power station packs 3000Wh LiFePO4 battery with 3000W continuous output (6000W peak) from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Cycle life >=3000 cycles. Charging via solar panel, AC mains, or 12V car. Weight 28 kg with trolley and wheels. MOQ 100 pcs, lead time 25-35 days. 24-month warranty. CE, FCC, RoHS, UN38.3 certified.',
    applications: 'Outdoor construction sites, emergency home backup, camping, medical rescue, off-grid workshops.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-3000' },
      { key: 'Capacity', value: '3000Wh' },
      { key: 'Battery Type', value: 'LiFePO4' },
      { key: 'Continuous Output', value: '3000W' },
      { key: 'Peak Output', value: '6000W' },
      { key: 'Cycle Life', value: '>=3000 cycles' },
      { key: 'Weight', value: '28 kg' },
      { key: 'Charging Methods', value: 'Solar / AC / Car' },
    ],
    features: [
      '3000Wh LiFePO4 battery with >=3000 cycle life',
      '3000W continuous / 6000W peak pure sine wave output',
      'Triple charging: solar panel, AC mains, 12V car socket',
      'Trolley design with wheels for easy transport at 28 kg',
    ],
    faq: [
      { question: 'What is the MOQ for the 3000W power station?', answer: 'MOQ is 100 pcs. Volume pricing starts at 200 pcs with 15% discount.' },
      { question: 'What certifications does this unit have?', answer: 'CE, FCC, RoHS, UN38.3 certified. ISO 9001 factory.' },
      { question: 'What is the lead time?', answer: '25-35 days depending on order volume and custom configuration.' },
      { question: 'Can I customise the casing colour or branding?', answer: 'Yes. Custom colours, logo printing, and private-label packaging from 200 pcs.' },
      { question: 'What is the warranty period?', answer: '24-month warranty against manufacturing defects. Replacement shipped within 72 hours.' },
      { question: 'How long does solar charging take?', answer: 'Full charge in 4-6 hours with 2x300W solar panels (not included).' },
      { question: 'Can it run a refrigerator?', answer: 'Yes. 3000W continuous output powers most household appliances including refrigerators and power tools.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '100 pcs',
      leadTime: '25-35 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'UN38.3', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1620216503901-515bb5c34c30?w=900&q=85',
  },
  'foldable-solar-panel-200w': {
    name: '200W Foldable Solar Panel',
    category: 'solar',
    badge: 'New',
    description: '200W foldable monocrystalline solar panel with ETFE surface. Folds to 550x450x50 mm, weighs 5.2 kg. IP65 waterproof with 5000+ fold cycles.',
    geoDescription: 'HousePlus 200W foldable solar panel features monocrystalline cells with ETFE surface from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Folds to 550x450x50 mm, unfolds to 1100x900x25 mm. Weight 5.2 kg. IP65 waterproof. 5000+ fold cycles. MOQ 100 pcs, lead time 20-25 days. 24-month warranty. CE, IEC, RoHS certified.',
    applications: 'Camping, RV power, emergency backup, outdoor adventures, off-grid hiking.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-200F' },
      { key: 'Peak Power', value: '200W' },
      { key: 'Cell Type', value: 'Monocrystalline ETFE' },
      { key: 'Folded Size', value: '550x450x50 mm' },
      { key: 'Unfolded Size', value: '1100x900x25 mm' },
      { key: 'Weight', value: '5.2 kg' },
      { key: 'IP Rating', value: 'IP65' },
      { key: 'Fold Cycles', value: '>=5000' },
    ],
    features: [
      'ETFE surface for superior light transmission and durability',
      'Folds to compact 550x450x50 mm for easy storage and transport',
      '5000+ fold cycles tested -- built for frequent outdoor use',
      'IP65 waterproof rating -- performs in rain and dust conditions',
    ],
    faq: [
      { question: 'What is the MOQ for foldable panels?', answer: 'MOQ is 100 pcs. Volume pricing from 300 pcs with 10% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders. 30 days for custom colours or branding.' },
      { question: 'Can I order custom carrying bags?', answer: 'Yes. Custom branded carrying bags and packaging from MOQ 100 pcs.' },
      { question: 'What connectors are included?', answer: 'MC4 connectors standard. Anderson and XT60 available on request.' },
      { question: 'What is the warranty?', answer: '24-month warranty against manufacturing defects.' },
      { question: 'How durable is the folding mechanism?', answer: 'Tested to 5000+ fold cycles without performance degradation.' },
      { question: 'Can it charge a power station directly?', answer: 'Yes. Compatible with most power stations via MC4 or adapter cables.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '100 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'IEC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1548613053-220e75581890?w=900&q=85',
  },
  'home-energy-storage-5000w': {
    name: '5000W Home Energy Storage System',
    category: 'solar',
    badge: 'New',
    description: '5000Wh modular LiFePO4 home energy storage system with 5000W output (10000W peak). Grid-tie/off-grid switchable. Cycle life >=6000.',
    geoDescription: 'HousePlus 5000W home energy storage system features modular 5000Wh LiFePO4 battery with 5000W continuous output (10000W peak) from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Grid-tie and off-grid modes switchable. Cycle life >=6000. MOQ 50 pcs, lead time 30-35 days. 24-month warranty. CE, IEC, RoHS, ISO 9001 certified.',
    applications: 'Home backup power, solar self-consumption, peak-valley electricity arbitrage, commercial microgrids.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-5000H' },
      { key: 'Capacity', value: '5000Wh modular' },
      { key: 'Battery Type', value: 'LiFePO4' },
      { key: 'Continuous Output', value: '5000W' },
      { key: 'Peak Output', value: '10000W' },
      { key: 'Cycle Life', value: '>=6000 cycles' },
      { key: 'Grid Modes', value: 'Grid-tie / Off-grid' },
      { key: 'Expandable', value: 'Up to 30kWh' },
    ],
    features: [
      'Modular design expandable from 5kWh to 30kWh with parallel connection',
      'Grid-tie and off-grid modes with seamless automatic switching',
      '>=6000 cycle life LiFePO4 cells -- 10+ year design lifespan',
      'Smart BMS with cell balancing, temperature control and overcurrent protection',
    ],
    faq: [
      { question: 'What is the MOQ for home storage systems?', answer: 'MOQ is 50 pcs. Volume pricing from 100 pcs with 18% discount.' },
      { question: 'What is the lead time?', answer: '30-35 days due to BMS programming and safety testing requirements.' },
      { question: 'Can the system be expanded?', answer: 'Yes. Modular design supports parallel expansion up to 30kWh total capacity.' },
      { question: 'What inverter compatibility?', answer: 'Compatible with most 48V hybrid inverters. Integration support provided.' },
      { question: 'What is the warranty?', answer: '24-month warranty. Extended warranty options available for 100+ unit orders.' },
      { question: 'Do you provide installation guides?', answer: 'Yes. Detailed installation manuals in 5 languages provided with each order.' },
      { question: 'Can I customise the enclosure colour?', answer: 'Yes. White and black standard. Custom colours from 100 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '50 pcs',
      leadTime: '30-35 days',
      warranty: '24 months',
      certifications: ['CE', 'IEC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900&q=85',
  },
  'power-bank-60w-pd': {
    name: '60W PD Fast Charging Power Bank',
    category: 'electronics',
    badge: 'Popular',
    description: '20000mAh power bank with 60W PD fast charging and QC3.0. Dual USB-C + USB-A output. Aluminium casing. 350g lightweight.',
    geoDescription: 'HousePlus 60W PD fast charging power bank delivers 20000mAh capacity with 60W Power Delivery and QC3.0 from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Dual USB-C + single USB-A output. Dimensions 150x75x25 mm, weight 350g. Aluminium casing for heat dissipation. MOQ 200 pcs, lead time 20-25 days. 24-month warranty. CE, FCC, RoHS certified.',
    applications: 'Laptop charging, smartphone fast charging, tablet power, travel backup, business trips.',
    specs: [
      { key: 'SKU', value: 'HP-3C-60W' },
      { key: 'Capacity', value: '20000mAh' },
      { key: 'Max Output', value: '60W PD + QC3.0' },
      { key: 'Ports', value: '2xUSB-C + 1xUSB-A' },
      { key: 'Dimensions', value: '150x75x25 mm' },
      { key: 'Weight', value: '350g' },
      { key: 'Material', value: 'Aluminium Alloy' },
      { key: 'Input', value: 'USB-C PD 60W' },
    ],
    features: [
      '60W PD output charges MacBook Air to 50% in 30 minutes',
      '20000mAh capacity -- 4+ full charges for most smartphones',
      'Aluminium alloy casing for efficient heat dissipation',
      'Simultaneous 3-device charging with intelligent power allocation',
    ],
    faq: [
      { question: 'What is the MOQ for power banks?', answer: 'MOQ is 200 pcs. Volume pricing from 1000 pcs with 15% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders. 30 days for custom colours or branding.' },
      { question: 'Can I order custom colours?', answer: 'Yes. Space grey, silver, and rose gold standard. Custom Pantone from 500 pcs.' },
      { question: 'What devices does 60W PD support?', answer: 'MacBook Air/Pro, iPad Pro, iPhone, Samsung Galaxy, Steam Deck, and most USB-C laptops.' },
      { question: 'What is the warranty?', answer: '24-month warranty against manufacturing defects.' },
      { question: 'Do you provide OEM packaging?', answer: 'Yes. Custom boxes, manuals, and branding from MOQ 200 pcs.' },
      { question: 'Can I print my logo on the power bank?', answer: 'Yes. Laser engraving and silk-screen printing available from 300 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '200 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1609091839311-d53681962025?w=900&q=85',
  },
  'lifepo4-battery-12v100ah': {
    name: '12V 100Ah LiFePO4 Battery',
    category: 'solar',
    badge: 'Best Seller',
    description: '12V 100Ah LiFePO4 deep cycle battery with 1280Wh capacity. Integrated BMS. 3000+ cycles. 12.5 kg. UN38.3 certified for shipping.',
    geoDescription: 'HousePlus 12V 100Ah LiFePO4 battery delivers 1280Wh capacity with 3000+ cycle life from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Integrated BMS with cell balancing and temperature management. Dimensions 330x175x220 mm, weight 12.5 kg (58% lighter than equivalent AGM). Operating temperature -20C to +60C. MOQ 50 pcs, lead time 25-30 days. 24-month warranty. CE, IEC, RoHS, UN38.3 certified.',
    applications: 'RV house batteries, marine systems, solar energy storage, UPS backup, off-grid cabins.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-12V100' },
      { key: 'Capacity', value: '100Ah (1280Wh)' },
      { key: 'Battery Type', value: 'LiFePO4' },
      { key: 'Cycle Life', value: '>=3000 cycles' },
      { key: 'Dimensions', value: '330x175x220 mm' },
      { key: 'Weight', value: '12.5 kg' },
      { key: 'Operating Temp', value: '-20C to +60C' },
      { key: 'BMS', value: 'Integrated 100A' },
    ],
    features: [
      '3000+ deep discharge cycles -- 5x lifespan of equivalent lead-acid batteries',
      'Integrated 100A BMS with overcharge, over-discharge, and short-circuit protection',
      '12.5 kg -- 58% lighter than 100Ah AGM battery for easier installation',
      'Wide operating temperature: -20C to +60C for extreme climate reliability',
    ],
    faq: [
      { question: 'What is the MOQ for LiFePO4 batteries?', answer: 'MOQ is 50 pcs. Volume pricing from 200 pcs with 20% discount.' },
      { question: 'Can these replace lead-acid batteries?', answer: 'Yes. Direct drop-in replacement for 12V AGM/gel batteries. Same dimensions, 58% lighter.' },
      { question: 'What is the lead time?', answer: '25-30 days. UN38.3 safety testing required for each production batch.' },
      { question: 'Are they safe for air freight?', answer: 'Yes. UN38.3 certified for air, sea, and land transport worldwide.' },
      { question: 'What is the warranty?', answer: '24-month warranty. Extended to 36 months for 500+ unit orders.' },
      { question: 'Can batteries be connected in parallel?', answer: 'Yes. Up to 4 batteries in parallel for 400Ah total capacity. BMS handles balancing automatically.' },
      { question: 'Do you provide terminal adapters?', answer: 'Yes. M8 bolt terminals standard. Copper bus bars and adapters included from 100 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '50 pcs',
      leadTime: '25-30 days',
      warranty: '24 months',
      certifications: ['CE', 'IEC', 'RoHS', 'UN38.3', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1619641151040-af3bf8325790?w=900&q=85',
  },
  'outdoor-power-station-600w': {
    name: '600W Outdoor Power Station',
    category: 'solar',
    badge: 'New',
    description: '600Wh LiFePO4 outdoor power station with 600W pure sine wave output. 2xAC + 2xUSB + 1xDC. 7.2 kg with handle. Solar/AC/car charging.',
    geoDescription: 'HousePlus 600W outdoor power station features 600Wh LiFePO4 battery with 600W pure sine wave output from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. 2xAC + 2xUSB + 1xDC output ports. 7.2 kg with ergonomic handle. Charging via 120W solar, AC mains, or 12V car. THD <3%. MOQ 100 pcs, lead time 20-25 days. 24-month warranty. CE, FCC, RoHS certified.',
    applications: 'Camping, outdoor events, emergency backup, construction sites, mobile workshops.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-600O' },
      { key: 'Capacity', value: '600Wh' },
      { key: 'Battery Type', value: 'LiFePO4' },
      { key: 'Continuous Output', value: '600W' },
      { key: 'Output Ports', value: '2xAC + 2xUSB + 1xDC' },
      { key: 'Weight', value: '7.2 kg' },
      { key: 'Solar Input', value: '120W max' },
      { key: 'THD', value: '<3%' },
    ],
    features: [
      '600Wh LiFePO4 battery with 2000+ cycle life for long-term reliability',
      '600W pure sine wave inverter (THD <3%) -- safe for sensitive electronics',
      '5 simultaneous output ports: 2xAC, 2xUSB, 1xDC for versatile charging',
      'Triple charging: 120W solar, AC mains, or 12V car for flexible recharging',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 100 pcs. Volume pricing from 500 pcs with 12% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders.' },
      { question: 'Can it run a refrigerator?', answer: 'Yes. 600W continuous output powers mini-fridges and camping coolers up to 400W.' },
      { question: 'How long does solar charging take?', answer: 'Full charge in 5-7 hours with 120W solar panel (not included).' },
      { question: 'What is the warranty?', answer: '24-month warranty against manufacturing defects.' },
      { question: 'Can I customise the colour?', answer: 'Yes. Black and orange standard. Custom colours from 300 pcs.' },
      { question: 'Do you provide carrying cases?', answer: 'Yes. Custom branded EVA carrying cases available from 200 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '100 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1624452085375-343547842776?w=900&q=85',
  },
  'mppt-controller-40a': {
    name: 'MPPT 40A Solar Charge Controller',
    category: 'solar',
    description: 'MPPT 40A solar charge controller with >=98% efficiency. Auto 12V/24V detection. LCD display. Supports lead-acid, gel, and LiFePO4 batteries.',
    geoDescription: 'HousePlus MPPT 40A solar charge controller achieves >=98% peak charging efficiency from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. 40A rated current. Auto 12V/24V detection. LCD display with real-time monitoring. Supports lead-acid, gel, and LiFePO4 batteries. 4-layer protection. MOQ 100 pcs, lead time 20-25 days. 24-month warranty. CE, RoHS certified.',
    applications: 'Off-grid solar systems, RV solar charging, remote monitoring stations, agricultural solar pumps.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-MPPT40' },
      { key: 'Rated Current', value: '40A' },
      { key: 'Efficiency', value: '>=98%' },
      { key: 'Auto Detection', value: '12V / 24V' },
      { key: 'Battery Types', value: 'Lead-acid / Gel / LiFePO4' },
      { key: 'Display', value: 'LCD' },
      { key: 'Protection', value: 'Overcharge / Over-discharge / Short / Reverse' },
      { key: 'Switching', value: '150kHz MOSFET' },
    ],
    features: [
      '>=98% peak MPPT efficiency -- 25-30% more energy than PWM controllers',
      'Auto 12V/24V battery detection -- no manual configuration required',
      'LCD display shows PV voltage, battery voltage, charge current and status',
      'Comprehensive protection: overcharge, over-discharge, short-circuit, reverse polarity',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 100 pcs. Volume pricing from 500 pcs with 15% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders.' },
      { question: 'Does it work with 48V systems?', answer: 'This model supports 12V and 24V only. 48V models available on request.' },
      { question: 'Can I customise the firmware?', answer: 'Yes. OEM firmware with custom charging curves and branding from 500 pcs.' },
      { question: 'What is the warranty?', answer: '24-month warranty against manufacturing defects.' },
      { question: 'What is the max PV input?', answer: '520W at 12V, 1040W at 24V. Open circuit voltage max 100V.' },
      { question: 'Do you provide mounting accessories?', answer: 'Yes. DIN rail mount and wall mount brackets included from 100 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '100 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1558444458-5f75bc94476c?w=900&q=85',
  },
  'magnetic-power-bank-10000mah': {
    name: '10000mAh Magnetic Wireless Power Bank',
    category: 'electronics',
    badge: 'New',
    description: '10000mAh MagSafe-compatible magnetic wireless power bank with 15W wireless and 20W PD USB-C. 220g ultra-light. PC+ABS fire-resistant.',
    geoDescription: 'HousePlus 10000mAh magnetic wireless power bank features 15W MagSafe-compatible charging and 20W PD USB-C from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Dimensions 108x68x12 mm, weight 220g. PC+ABS fire-resistant material. MOQ 300 pcs, lead time 20-25 days. 24-month warranty. CE, FCC, RoHS certified.',
    applications: 'iPhone wireless charging, smartphone backup, travel, daily commuting, business use.',
    specs: [
      { key: 'SKU', value: 'HP-3C-MAG10K' },
      { key: 'Capacity', value: '10000mAh' },
      { key: 'Wireless Output', value: '15W MagSafe' },
      { key: 'Wired Output', value: '20W PD USB-C' },
      { key: 'Dimensions', value: '108x68x12 mm' },
      { key: 'Weight', value: '220g' },
      { key: 'Material', value: 'PC+ABS Fire-resistant' },
      { key: 'Compatibility', value: 'iPhone 12/13/14/15 series' },
    ],
    features: [
      '15W MagSafe-compatible magnetic alignment for precise wireless charging',
      '10000mAh capacity provides 1.5x full charges for iPhone 15 Pro',
      '20W PD USB-C for wired fast charging when magnetic is not needed',
      'PC+ABS fire-resistant housing with overheat and short-circuit protection',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 300 pcs. Volume pricing from 1000 pcs with 18% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders. 30 days for custom colours.' },
      { question: 'Does it work with non-MagSafe cases?', answer: 'Magnetic charging requires MagSafe cases or direct contact. Non-MagSafe cases may reduce efficiency.' },
      { question: 'Can I print my logo?', answer: 'Yes. Laser engraving and colour printing from 500 pcs.' },
      { question: 'What is the warranty?', answer: '24-month warranty against manufacturing defects.' },
      { question: 'Does it charge Android phones?', answer: 'Yes. 15W Qi wireless and 20W USB-C PD compatible with all Qi-enabled devices.' },
      { question: 'Can I order custom colours?', answer: 'Yes. White, black, and blue standard. Custom Pantone from 500 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '300 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=900&q=85',
  },
  'pure-sine-inverter-2000w': {
    name: '2000W Pure Sine Wave Inverter',
    category: 'solar',
    badge: 'CE Certified',
    description: '2000W pure sine wave inverter with 4000W surge. >=92% efficiency. THD <3%. 12V/24V/48V input. 110V/220V output. 8 protection layers.',
    geoDescription: 'HousePlus 2000W pure sine wave inverter delivers 2000W continuous (4000W surge) with >=92% efficiency and THD <3% from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Input: 12V/24V/48V selectable. Output: 110V/220V selectable. 8-layer protection system. MOQ 50 pcs, lead time 25-30 days. 24-month warranty. CE, RoHS certified.',
    applications: 'RV power systems, off-grid cabins, backup power, mobile workshops, marine applications.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-INV2K' },
      { key: 'Rated Power', value: '2000W' },
      { key: 'Surge Power', value: '4000W' },
      { key: 'Efficiency', value: '>=92%' },
      { key: 'THD', value: '<3%' },
      { key: 'Input Voltage', value: '12V / 24V / 48V' },
      { key: 'Output Voltage', value: '110V / 220V' },
      { key: 'Protection', value: '8-layer (overload/overtemp/short/low voltage/reverse)' },
    ],
    features: [
      'Pure sine wave output (THD <3%) -- safe for sensitive electronics and medical devices',
      '>=92% conversion efficiency -- minimal energy loss during DC-AC conversion',
      '8-layer protection: overload, over-temperature, short-circuit, low voltage, reverse polarity',
      'Selectable input (12V/24V/48V) and output (110V/220V) for global compatibility',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 50 pcs. Volume pricing from 200 pcs with 15% discount.' },
      { question: 'What is the lead time?', answer: '25-30 days. Each unit undergoes 4-hour burn-in testing.' },
      { question: 'Can it run a refrigerator?', answer: 'Yes. 2000W continuous / 4000W surge handles most household refrigerators (500-1500W startup).' },
      { question: 'What battery voltage should I use?', answer: '12V for <1000W loads, 24V for 1000-2000W, 48V for maximum efficiency at 2000W.' },
      { question: 'What is the warranty?', answer: '24-month warranty. Extended to 36 months for 200+ unit orders.' },
      { question: 'Do you provide installation cables?', answer: 'Yes. Copper cables and lugs included from 50 pcs. Custom cable lengths available.' },
      { question: 'Can I customise the enclosure?', answer: 'Yes. Aluminium and steel enclosures. Custom colours from 100 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '50 pcs',
      leadTime: '25-30 days',
      warranty: '24 months',
      certifications: ['CE', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1620216503901-515bb5c34c30?w=900&q=85',
  },
  'flexible-solar-panel-400w': {
    name: '400W Semi-Flexible Solar Panel',
    category: 'solar',
    badge: 'New',
    description: '400W semi-flexible monocrystalline solar panel with ETFE surface. 30 degree bend radius. 8.5 kg (60% lighter than glass). 3mm thickness. 3M adhesive or screw mount.',
    geoDescription: 'HousePlus 400W semi-flexible solar panel features monocrystalline cells with ETFE surface from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. 30 degree maximum bend radius. 8.5 kg -- 60% lighter than equivalent glass panels. 3mm thickness. Mounting: 3M adhesive backing or screw holes. MOQ 50 pcs, lead time 25-30 days. 24-month warranty. CE, IEC, RoHS certified.',
    applications: 'RV curved roofs, marine decks, vehicle roofs, curved architectural surfaces, boat cabins.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-400F' },
      { key: 'Peak Power', value: '400W' },
      { key: 'Cell Type', value: 'Monocrystalline ETFE' },
      { key: 'Bend Radius', value: 'Up to 30 degrees' },
      { key: 'Weight', value: '8.5 kg' },
      { key: 'Thickness', value: '3 mm' },
      { key: 'Mounting', value: '3M adhesive / Screw holes' },
      { key: 'Efficiency', value: '>=21.4%' },
    ],
    features: [
      '30 degree bend radius -- conforms to curved RV roofs and boat decks',
      '8.5 kg -- 60% lighter than 400W glass panels for weight-sensitive applications',
      '3mm ultra-thin profile -- minimal wind resistance and aesthetic integration',
      'Dual mounting: 3M VHB adhesive backing or pre-drilled screw holes',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 50 pcs. Volume pricing from 200 pcs with 15% discount.' },
      { question: 'What is the lead time?', answer: '25-30 days. ETFE lamination requires specialised equipment.' },
      { question: 'Can it be walked on?', answer: 'Not recommended. ETFE surface is durable but not rated for foot traffic.' },
      { question: 'How is it different from glass panels?', answer: '60% lighter, 3mm thin, bendable to 30 degrees. Lower efficiency degradation over time due to ETFE resilience.' },
      { question: 'What is the warranty?', answer: '24-month warranty. Extended to 36 months for 200+ unit orders.' },
      { question: 'Can I order custom sizes?', answer: 'Yes. Custom dimensions from 100 pcs. Max single panel 600W.' },
      { question: 'Is it suitable for marine use?', answer: 'Yes. Salt spray tested. IP65 rated. 3M adhesive withstands marine conditions.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '50 pcs',
      leadTime: '25-30 days',
      warranty: '24 months',
      certifications: ['CE', 'IEC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=900&q=85',
  },
  'solar-generator-kit-300w': {
    name: 'Portable Solar Generator Kit 300W',
    category: 'solar',
    badge: 'Popular',
    description: 'All-in-one 300W solar generator kit: 100W panel + 300Wh LiFePO4 power station + cables + carry bag. 12 kg total. 6-8 hours solar charge.',
    geoDescription: 'HousePlus 300W portable solar generator kit includes 100W solar panel, 300Wh LiFePO4 power station, connection cables, and carry bag from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. 300W pure sine wave output. Solar charge in 6-8 hours. Total kit weight 12 kg. MOQ 100 pcs, lead time 20-25 days. 24-month warranty. CE, FCC, RoHS certified.',
    applications: 'Camping, emergency backup, outdoor activities, remote work, disaster relief.',
    specs: [
      { key: 'SKU', value: 'HP-SOL-KIT300' },
      { key: 'Panel Power', value: '100W' },
      { key: 'Battery Capacity', value: '300Wh LiFePO4' },
      { key: 'Inverter Output', value: '300W pure sine wave' },
      { key: 'Solar Charge Time', value: '6-8 hours' },
      { key: 'Kit Weight', value: '12 kg' },
      { key: 'Cycle Life', value: '>=2000 cycles' },
      { key: 'Included', value: 'Panel + Station + Cables + Bag' },
    ],
    features: [
      'Complete kit: 100W panel, 300Wh power station, cables, and carry bag',
      '300Wh LiFePO4 battery with >=2000 cycle life for long-term reliability',
      '300W pure sine wave output -- safe for laptops, phones, and small appliances',
      'Solar charge in 6-8 hours -- self-sufficient off-grid power solution',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 100 pcs. Volume pricing from 500 pcs with 12% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders.' },
      { question: 'Can I buy components separately?', answer: 'Yes. Panel, power station, and accessories available as individual SKUs.' },
      { question: 'What devices can it power?', answer: 'Laptops, phones, LED lights, small fans, and routers up to 300W total.' },
      { question: 'What is the warranty?', answer: '24-month warranty on all kit components.' },
      { question: 'Can I customise the carry bag?', answer: 'Yes. Custom branded carry bags from 200 pcs.' },
      { question: 'Is the kit suitable for air freight?', answer: 'Yes. UN38.3 certified battery. Individual packaging meets IATA requirements.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '100 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1548613053-220e75581890?w=900&q=85',
  },
  'smart-wifi-plug-meter': {
    name: 'Smart WiFi Plug with Energy Meter',
    category: 'appliances',
    badge: 'New',
    description: 'Smart WiFi plug with real-time energy monitoring. 16A/3680W max. 2.4GHz WiFi. Alexa/Google Home/SmartLife compatible. 85x85x35 mm.',
    geoDescription: 'HousePlus smart WiFi plug with energy meter supports 16A/3680W max load and real-time power monitoring from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. 2.4GHz WiFi. Compatible with Alexa, Google Home, and SmartLife APP. Dimensions 85x85x35 mm. MOQ 300 pcs, lead time 20-25 days. 24-month warranty. CE, FCC, RoHS certified.',
    applications: 'Home automation, energy monitoring, smart offices, rental properties, retail display control.',
    specs: [
      { key: 'SKU', value: 'HP-HA-WIFI10' },
      { key: 'Max Load', value: '16A / 3680W' },
      { key: 'WiFi', value: '2.4GHz' },
      { key: 'Compatibility', value: 'Alexa / Google Home / SmartLife' },
      { key: 'Dimensions', value: '85x85x35 mm' },
      { key: 'Monitoring', value: 'Real-time kWh & power' },
      { key: 'Voltage', value: '100-240V AC' },
      { key: 'App', value: 'SmartLife / Tuya' },
    ],
    features: [
      'Real-time energy monitoring with kWh, voltage, current, and power display',
      '16A / 3680W maximum load -- handles high-power appliances safely',
      'Voice control via Alexa and Google Home with SmartLife APP integration',
      'Timer and scheduling functions for automated energy savings',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 300 pcs. Volume pricing from 1000 pcs with 15% discount.' },
      { question: 'What is the lead time?', answer: '20-25 days for standard orders.' },
      { question: 'Can I white-label the APP?', answer: 'Yes. OEM APP branding and custom firmware from 1000 pcs.' },
      { question: 'Does it work with 5GHz WiFi?', answer: 'No. 2.4GHz only. Compatible with all standard 2.4GHz routers.' },
      { question: 'What is the warranty?', answer: '24-month warranty against manufacturing defects.' },
      { question: 'Can I order custom colours?', answer: 'Yes. White standard. Custom colours from 500 pcs.' },
      { question: 'Is the APP free for end users?', answer: 'Yes. SmartLife APP is free. White-label APP requires one-time setup fee.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '300 pcs',
      leadTime: '20-25 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1558002038-1091a166111c?w=900&q=85',
  },
  'usb-c-cable-100w-5a': {
    name: 'Type-C 100W Fast Charging Cable (5A)',
    category: 'electronics',
    badge: 'Best Seller',
    description: '100W PD USB-C to USB-C cable with 5A current. 1m/2m lengths. Nylon braided with aluminium connectors. 10000+ bend cycles. 480Mbps data.',
    geoDescription: 'HousePlus Type-C 100W fast charging cable supports 5A current and 100W Power Delivery from a 20,000 m2 ISO 9001 certified factory. Since 2010, we have supplied 441+ wholesale clients across 53+ countries. Nylon braided with aluminium alloy connectors. 10000+ bend cycle tested. 480Mbps data transfer. 1m and 2m lengths. MOQ 500 pcs, lead time 15-20 days. 24-month warranty. CE, FCC, RoHS certified.',
    applications: 'MacBook Pro charging, iPad Pro, Steam Deck, Android fast charging, data transfer.',
    specs: [
      { key: 'SKU', value: 'HP-3C-TC100W' },
      { key: 'Max Power', value: '100W PD' },
      { key: 'Current', value: '5A' },
      { key: 'Length', value: '1m / 2m' },
      { key: 'Material', value: 'Nylon braided + Aluminium' },
      { key: 'Bend Cycles', value: '>=10000' },
      { key: 'Data Speed', value: '480 Mbps' },
      { key: 'Compatibility', value: 'USB-C devices' },
    ],
    features: [
      '100W PD power delivery -- charges MacBook Pro and laptops at full speed',
      '5A current capacity with E-Marker chip for safe high-power charging',
      'Nylon braided jacket with aluminium connectors -- 10000+ bend cycle durability',
      '480Mbps data transfer -- sync files while charging simultaneously',
    ],
    faq: [
      { question: 'What is the MOQ?', answer: 'MOQ is 500 pcs. Volume pricing from 2000 pcs with 20% discount.' },
      { question: 'What is the lead time?', answer: '15-20 days -- fastest in our product range due to automated cable production.' },
      { question: 'Can I order custom lengths?', answer: 'Yes. 0.5m to 3m custom lengths from 1000 pcs.' },
      { question: 'Can I print my logo on the connectors?', answer: 'Yes. Laser engraving on aluminium connectors from 500 pcs.' },
      { question: 'What is the warranty?', answer: '24-month warranty against cable fraying and connector failure.' },
      { question: 'Does it support video output?', answer: 'No. This is a charging and data cable only. No DisplayPort Alt Mode support.' },
      { question: 'Can I order custom colours?', answer: 'Yes. Black, grey, and red standard. Custom Pantone from 1000 pcs.' },
      { question: 'Which countries do you export to?', answer: '53+ countries including Germany, UAE, Nigeria, Kenya, South Africa, and Tanzania.' },
    ],
    b2bInfo: {
      moq: '500 pcs',
      leadTime: '15-20 days',
      warranty: '24 months',
      certifications: ['CE', 'FCC', 'RoHS', 'ISO 9001'],
      oemOdm: true,
      factorySize: '20,000 m2',
      foundedYear: 2010,
      exportCountries: 53,
      wholesaleClients: 441,
    },
    coverImage: 'https://images.unsplash.com/photo-1619193100632-68046777174b?w=900&q=85',
  },
};

export const CATEGORY_CONFIG = {
  solar: {
    label: 'Solar Energy Systems',
    color: 'text-amber-700',
    bg: 'bg-amber-50 border-amber-200',
    icon: '☀️',
  },
  appliances: {
    label: 'Home Appliances',
    color: 'text-blue-700',
    bg: 'bg-blue-50 border-blue-200',
    icon: '🏠',
  },
  electronics: {
    label: '3C Electronics',
    color: 'text-purple-700',
    bg: 'bg-purple-50 border-purple-200',
    icon: '📱',
  },
} as const;
